name: Tests

on:
  pull_request:
    branches: [ main, dev ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-hex:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: determine short GIT hash
        id:   vars
        run:  echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: build docker image
        run:  docker compose build
      - name: build hex file
        run:  docker compose run --rm build-hex
      - name: upload build artifact
        uses: actions/upload-artifact@v3
        with:
            name: BlinkLed-${{ steps.vars.outputs.sha_short }}
            path: nucleo-f446re/BlinkLed/build/BlinkLed.hex
